### ISSUE TITLE
新規revision通知

### ISSUE THREAD

**Issue by su8ru** [afes-website/back#29]
Slackでいいんじゃないかなと

**Comment by ibuki2003** [comment]
~メール送って転送 が楽かもな〜~
laravelはslack対応してるんだったかもしれん logと一緒にやっちゃおう(致命的エラー時通知とか)

**Comment by su8ru** [comment]
ついでに公開通知とかもあるといいかもね

**Comment by ibuki2003** [comment]
これは投稿者へ?(めんどくさそう…)

**Comment by su8ru** [comment]
や、全部Slack垂れ流しでいいと思う

**Comment by ibuki2003** [comment]
なるほど adminの行動が見えればよいのね
